name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deps
        # due to react-diff-viewer-continued: 4.0.3 (no support for react 19)
        run: npm ci --force

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test
